### ISSUE TITLE
Unable to get token

### ISSUE THREAD

**Issue by spdvi** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#1]
With the documentation provided it is not possible to get a token.
What format should I pass the email and password? Json, form-data, other?

**Comment by JavierDuque450** [comment]
Hello,

The issue should now be fixed. You should be able to login to the system through the URI **http://apibaleart.duquevela.com/public/api/login** as specified in the attached PDF with the credentials given to you (same parameter names) in the README file. We recommend using the  **x-www-form-urlencoded** format.

Please tell us whether the issue persists or not so we can close this issue.

**Comment by spdvi** [comment]
It is working smoothly now.
Thanks, you can close this issue.
