### ISSUE TITLE
Error al cargar datos de fotografies

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#10]
Despues de varios intentos y comprobación de otros compañeros, sale que al intentar revisar el get de fotografies da error, no se si se debe a que se hace algun paso incorreto o es un error que hay
![image](https://user-images.githubusercontent.com/77690759/156377581-9aeae62f-87c8-4955-9440-36b07a87ebc3.png)

**Comment by JavierDuque450** [comment]
Buenas tardes,

Sentimos las molestias, ha sido un error a la hora de migrar una API nueva para nuestro proyecto. Los problemas producidos por este fallo deberian estar solucionados.

Disculpen las molestias
