### ISSUE TITLE
No funciona get Espais

### ISSUE THREAD

**Issue by joanandreu99** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#11]
Hola Bones
He provat de que me tornes tots els espais i hem dona error, no se si ho faig malement o no va la api. Si ho podeu revisar lo mes rapid possible estaria molt be Gracis.

![image](https://user-images.githubusercontent.com/77398902/156391499-9ac749ee-5944-410e-aafa-5803200d577f.png)

![image](https://user-images.githubusercontent.com/77398902/156391414-22eb952f-613d-4cf8-855a-3a19bb01b8d4.png)

**Comment by JavierDuque450** [comment]
Buenas tardes,

Sentimos las molestias, ha sido un error a la hora de migrar una API nueva para nuestro proyecto. Los problemas producidos por este fallo deberian estar solucionados.

Disculpen las molestias

**Comment by joanandreu99** [comment]
Okey ja esta todo bien Gracias
