### ISSUE TITLE
Error a l'hora de fer POST a Espais

### ISSUE THREAD

**Issue by joanandreu99** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#12]
Deu ser la taula Espai que mos dona molt de fallos

![image](https://user-images.githubusercontent.com/77398902/156412239-d8270922-9987-49f1-927e-11a7f4e4a7b7.png)
![image](https://user-images.githubusercontent.com/77398902/156412280-09622f8d-1cd6-4739-9a95-c31733df1404.png)

**Comment by JavierDuque450** [comment]
Buenas tardes,

Sentimos las molestias, ha sido un error a la hora de migrar una API nueva para nuestro proyecto. Los problemas producidos por este fallo deberian estar solucionados.

Disculpen las molestias

**Comment by joanandreu99** [comment]
Okey ja funciona Gracias
