### ISSUE TITLE
Tablas intermedias

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#13]
- Por lo visto en la documentación, las tablas intermedias como las de traduccion que conectan idioma con el resto de tablas, u otras como ofrece_servicio no tienen la opción de get, es decir estas tablas intermedias que sirven para revisar que valores estan relacionados no tienen la opcion de ser consultadas, solo se puede insertar las relaciones y borrarlas pero no pueden consultarlas.

![image](https://user-images.githubusercontent.com/77690759/156583005-64cdab93-f91f-4dba-8227-daa00a0662c3.png)

Por ejemplo en el caso de la tabla de la imagen, se puede agregar la relacion y la descripcion correspondiente pero no se puede consultar

**Comment by JavierDuque450** [comment]
Eso es debido a una implementación de ORM en nuestras APIs que no ha sido posible implementar en la vuestra, ya que algunas de las claves extranjeras no quedaron correctamente definidas. En el ORM, al hacer por ejemplo una consulta a artista, dicha consulta incluriria también sus traducciones y otras relaciones posibles (obras, exposiciones...)

Si lo necesitaseis, no tendríamos problema en implementar GETs para las tablas intermedias para vuestra API

**Comment by BryanJT01** [comment]
Debido a que debemos elegir las opciones desde la interfaz para hacer las consultas, nos resulta necesario los GET, agradecemos que nos proporcionen las implementaciones a esas tablas

**Comment by JavierDuque450** [comment]
De acuerdo, hemos implementado GETs a las tablas necesarias. Si necesitais algo más no dudeis en hacernoslo saber
