### ISSUE TITLE
Feature request: localitats dels espais

### ISSUE THREAD

**Issue by JaumeOS** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#3]
Dins els espais la direcció hem vist que si que hi es pero també necessitam la localitat de cada espai. per exemple:

Espai
...
"id":1,
"localitat":"Inca"
...

Espai 2
...
"id":2,
"localitat":"Lloseta"
...

**Comment by JavierDuque450** [comment]
Bon dia,

Hem afegit aquesta característica a la API, baix el nombre de 'localitat', ho podeu comprovar ara al PDF. Per favor, comprovi que funcioni correctament per poder tancar aquesta Issue
