### ISSUE TITLE
Tipo de Usuario

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#4]
- Se ve que al crear o modificar un Usuario se agrega el tipo siendo estos Estandar, Gestor y Usuario. ¿Qué diferencia exacta hay con cada una de las opciones? ¿Segun como esta diseñado que limitaciones o ventajas tiene cada tipo de usuario?

**Comment by JavierDuque450** [comment]
Buenas tardes,

Muchas gracias por acercarte con la duda, ya que se trataba de un error en el PDF: el tercer tipo de usuario es ADMIN, no USUARI

En todo caso, las funciones de cada uno són:

- **ADMIN**: Gestionan el lugar web, pueden seleccionar espacios de forma que salgan como destacados y asignar gestores a diferentes espacios
- **GESTOR**: Son responsables de mantener los espacios que se les ha asignado
- **ESTANDARD**: Usuarios normales, pueden poner comentarios bajo los espacios.

Sientense libres de dejar otras dudas respecto a los usuarios o cerrar este Issue si no hay ninguna otra pregunta
