### ISSUE TITLE
Problema subiendo la imagen de perfil de los usuarios

### ISSUE THREAD

**Issue by JaumeOS** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#5]
Primero necesitamos saber que tipo de dato es cada cosa, por ejemplo en el pdf se especifican los parámetros que tenemos que usar pero no el tipo de dato de cada campo, por ejemplo: 
![image](https://user-images.githubusercontent.com/77398566/154287195-16999d02-c519-49ff-8e78-08af798f29c2.png)
el campo "img" no sabemos que tipo de datos es.

Despues el problema de subir la imágen:
![image](https://user-images.githubusercontent.com/77398566/154287396-689d6196-90ba-46be-9c2b-f10c8aecbb56.png)
Le pasamos por parámetro el campo "img" y el valor que le damos para probar si funciona es una url de una imágen de internet y nos devuelve status 200 OK pero no devuelve nada para comprobar que se ha introducido la imágen correctamente.
Despues hacemos el get de ese usuario y el campo "imgPerfil" es null:
![image](https://user-images.githubusercontent.com/77398566/154287865-e7e180da-a07b-4a68-b69e-bd2de2830d3a.png)

Saludos y muchas gracias.

**Comment by JaumeOS** [comment]
También he probado de en el body pasarle el campo "imgPerfil" como parámetro y tampoco funciona.

**Comment by JavierDuque450** [comment]
Buenos dias,

Las imagenes deben subirse en el formato **form-data**, asegurandose en Postman de elegir en el menú desplegable **File** para poder seleccionar el archivo que se quiere utilizar

![image](https://user-images.githubusercontent.com/77160740/154447666-dc890a80-d82c-4413-93e0-5578cef13dc8.png)

Hemos modificado la API para añadir un mensaje de error cuando no se puede subir una imagen, y actualizado el PDF para especificar el formato de datos de la API. Si no surge otro problema, se puede cerrar este Issue

**Comment by JaumeOS** [comment]
Perfecto ya funciona el post de las imágenes, pero el PDF no se ha actualizado con los tipos de datos de los parámetros.

**Comment by JavierDuque450** [comment]
Se nos olvidó hacer el push, ya deberia estar disponible.

Cierro la Issue ahora que funciona
