### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#6]
Para poder registrarse debe ser posible crear un usuario sin necesidad de token
![image](https://user-images.githubusercontent.com/77690759/154310644-35984dd3-fb6d-478f-8cb9-b4583e5ba5ff.png)
Al ser un nuevo usuario el que se esta registrando, no tiene token por lo que no se puede registrar, debe permitirse crear usuarios sin token

**Comment by JavierDuque450** [comment]
Buenos dias,

Hemos realizado el cambio
