### ISSUE TITLE
Control de parametres del Espai

### ISSUE THREAD

**Issue by joanandreu99** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#7]
falta de espacio:
- web
- telefono
- email
- valoración global (cada usuario da valoracion y se saca media) para eso solo se requiere que espacios tenga un campo de valoracion global y una conexion entre el id de Usuario i el id de Espacio y la valoracion individual.
- modalidad
- isDestacado boolean
sobra y se puede quitar:
- capaidad / superficie

falta de obra:
- fecha creacion

falta de usuario:
- telefono
- apellidos
- dni

para mostrar la modadlidad en los espacios, se debe crear una conexión intermedia entre modalidades y espacios en el que se recibe el id de ambos, asi un espacio pude mostrar diferentes modalidades de arte

Este es un mapa de como hemos visto como esta organizada la información para que la usen si es de utilidad o bien para rectificar por si hay algo que este mal interpretado.
![sdv](https://user-images.githubusercontent.com/77398902/154317123-ba8bcec1-5e13-4b76-8ab8-93b73957d59e.jpeg)

**Comment by joanandreu99** [comment]
Aquest document son els requisits si teniu un altre dubte consultau el pdf.
[Projecte_Art_Balear.pdf](https://github.com/CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori/files/8081965/Projecte_Art_Balear.pdf)

**Comment by joanandreu99** [comment]
Tambe necessitamos que les Modalidades tengan una traducción. (es decir: Tradueix_modalitats)

**Comment by spdvi** [comment]
Bones @joanandreu99, les específicacions de la informació que ha de tenir cada entitat estàn obertes i no ténen perquè coincidir amb les que hi ha al document proporcionat, a no ser que siguin estrictament necessàries.
Si no es un camp important com per exemple el identificador d'un espai, el nom la localitat o el tipus no cal que estigui. Si has de mester algun camp més els hi pots demanar si ho poden posar.
Sinò has d'adaptar la interfície a la informació que surt a la API.
També haurieu de mirar que hi hagi consistència entre el títol del Issue i lo que es demana. En el títol demanau per l'Espai i desprès als comentaris tb inclogueu obra, usuario i a un altre missatge les Modalitats. Es convenient tenir un ordre. Si es demana una funcionalitat diferent com per exemple incloure una traducció a les modalitats millor obrir un nou Issue.

**Comment by joanandreu99** [comment]
Okey Gracias.
