### ISSUE TITLE
Control de valoración

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#8]
Para poder gestionar una valoración de los espacios de la Api, se requiere de una conexión intermedia entre el id del Usuario y el id del Espacio que incluya un atributo de valoración individual.
También un atributo destacado de tipo boolean en los espacios que se hace con un "post" usando el id del espacio, para definirlo como true o false. Esto se hace fuera de la creación de un espacio debido a que es el administrador el que se encarga de destacarlos o no fuera por separado

**Comment by JavierDuque450** [comment]
Buenas tardes,

Hemos añadido la nueva relación a la API. Podréis ver en el PDF como acceder a ella y manipularla. Si surge algún problema o necesitáis algo más no dudeis en contactar
