### ISSUE TITLE
Gestion Usuario

### ISSUE THREAD

**Issue by BryanJT01** [CIFP-Pau-Casesnoves-DAW/baleart-public-duquegarciaspriori#9]
- Error al hacer PUT en la información del usuario, no se puede actualizar nada a menos de que se cambie el correo electronico lo cual no debe hacerse asi
- Hace falta un put y/o un delete para la imagen de perfil del usuario, solo esta el post

**Comment by JavierDuque450** [comment]
Buenos dias,

En principio, el error descrito en el primer punto deberia estar ya solucionado. 

Debido a una limitacion de PHP / Laravel, **no es posible hacer un PUT para una imagen**. Hemos actualizado la API para incluir un DELETE de imagen de usuario, pero no será posible crear una alternativa PUT para modificar: se tendrá que crear (POST) y eliminar (DELETE) únicamente

Muchas gracias por vuestra paciencia. Si sigue sin funcionar correctamente no duden en volver a contactar.
